name: Static Site

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:


jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      
      # configure gcloud `setup-gcloud` automatically
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: 'projects/84099340212/locations/global/workloadIdentityPools/github/providers/1660-repo'
          service_account: 'servattempt2@cs1660hws.iam.gserviceaccount.com'

      # upload files to GCS
      - id: 'upload-static-files'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: 'public'
          destination: '1660projbucket'
          parent: false
